import React from 'react';
import { X, ShieldCheck, FileText, Lock, AlertTriangle } from 'lucide-react';

interface LegalModalProps {
  type: 'privacy' | 'terms' | 'disclaimer' | null;
  onClose: () => void;
}

export const LegalModals: React.FC<LegalModalProps> = ({ type, onClose }) => {
  if (!type) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-md animate-in fade-in duration-200">
      <div 
        id="legal-modal-container"
        className="relative w-full max-w-2xl rounded-3xl bg-slate-900 border border-slate-800 shadow-2xl overflow-hidden text-slate-100 max-h-[85vh] flex flex-col"
      >
        {/* Header */}
        <div className="p-6 border-b border-slate-800 flex items-center justify-between bg-slate-950/50">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-emerald-500/10 border border-emerald-500/30 flex items-center justify-center text-emerald-400">
              <ShieldCheck className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-lg font-bold text-white font-['Space_Grotesk']">
                {type === 'privacy' && 'Privacy Policy & Statement Handling'}
                {type === 'terms' && 'Terms of Service & User Agreement'}
                {type === 'disclaimer' && 'Legal & Financial Disclaimers'}
              </h2>
              <p className="text-xs text-slate-400">
                Effective Date: August 2025 • United States
              </p>
            </div>
          </div>

          <button
            id="close-legal-modal-btn"
            onClick={onClose}
            className="p-2 rounded-xl text-slate-400 hover:text-white hover:bg-slate-800"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Body */}
        <div className="p-6 overflow-y-auto flex-1 space-y-4 text-xs text-slate-300 leading-relaxed font-sans">
          
          {type === 'privacy' && (
            <div className="space-y-4">
              <div className="p-4 rounded-xl bg-emerald-950/40 border border-emerald-500/30 text-emerald-300 text-xs space-y-2">
                <p className="font-bold text-sm text-white">BillGuard AI values your privacy.</p>
                <ul className="list-disc pl-4 space-y-1 text-slate-200">
                  <li>We do not ask for banking passwords or OTPs.</li>
                  <li>Uploaded files are used only for temporary subscription analysis.</li>
                  <li>We do not sell personal financial information.</li>
                  <li>Files may be automatically deleted after processing.</li>
                  <li>Users should remove sensitive information before uploading documents.</li>
                </ul>
                <p className="pt-1 text-slate-300 text-[11px]">
                  If you have any questions, contact: <a href="mailto:support@billguardai.com" className="text-emerald-400 underline">support@billguardai.com</a>
                </p>
              </div>

              <h4 className="text-sm font-bold text-white">1. Zero Banking Passwords or OTPs</h4>
              <p>
                BillGuard AI is a read-only informational analytical tool. We never request your online banking master passwords, account PINs, or one-time passcodes (OTPs).
              </p>

              <h4 className="text-sm font-bold text-white">2. Ephemeral Temporary Analysis</h4>
              <p>
                Uploaded bank statement files, screenshots, or pasted text are evaluated in temporary volatile memory solely to calculate recurring charges, price hikes, and potential savings.
              </p>

              <h4 className="text-sm font-bold text-white">3. No Sale of Financial Information</h4>
              <p>
                We do not sell, rent, monetize, or distribute personal financial or transactional data to data aggregators, advertisers, or third-party brokers.
              </p>
            </div>
          )}

          {type === 'terms' && (
            <div className="space-y-4">
              <h4 className="text-sm font-bold text-white">1. Informational & Analytical Nature</h4>
              <p>
                BillGuard AI is an automated productivity tool designed to help consumers audit transaction records. BillGuard AI is not a bank, depository institution, loan broker, or registered investment advisor.
              </p>

              <h4 className="text-sm font-bold text-white">2. AI Generated Correspondence</h4>
              <p>
                Cancellation letters and negotiation phone scripts generated by the AI are provided as draft templates for the user's convenience. The user retains sole discretion and responsibility for submitting communications to service providers.
              </p>

              <h4 className="text-sm font-bold text-white">3. Limitation of Liability</h4>
              <p>
                BillGuard AI does not guarantee that third-party merchants will honor fee waiver requests, promotional rate matches, or subscription refund demands.
              </p>
            </div>
          )}

          {type === 'disclaimer' && (
            <div className="space-y-4">
              <div className="p-3.5 rounded-xl bg-amber-950/40 border border-amber-500/30 text-amber-300 text-xs flex items-start gap-2">
                <AlertTriangle className="w-5 h-5 text-amber-400 shrink-0 mt-0.5" />
                <div>
                  <strong>Important Notice:</strong> BillGuard AI does not provide personalized legal, accounting, tax, or financial planning advice.
                </div>
              </div>

              <h4 className="text-sm font-bold text-white">Non-Banking Institution Status</h4>
              <p>
                “BillGuard AI is not a bank. Analysis is informational only. Files are encrypted and automatically deleted after processing. No financial advice is provided.”
              </p>

              <h4 className="text-sm font-bold text-white">Partner Links & Affiliation</h4>
              <p>
                Certain links featured on BillGuard AI are affiliate links. If you open a high-yield savings account or apply for a credit card through our links, we may receive partner compensation at no additional cost to you.
              </p>
            </div>
          )}

        </div>

        {/* Footer */}
        <div className="p-6 border-t border-slate-800 bg-slate-950/50 flex justify-end">
          <button
            onClick={onClose}
            className="px-5 py-2.5 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-bold text-xs"
          >
            I Understand & Agree
          </button>
        </div>
      </div>
    </div>
  );
};
